[package]
edition = "2024"
name = "format_sol"
version = "0.1.0"

[dependencies]
amf0 = {path = "../amf0"}
byteorder = "1"
format_core = {path = "../format_core"}
spatial_grid = {path = "../spatial_grid"}
thiserror = "2"
vector2d = {path = "../vector2d"}

[dev-dependencies]
pretty_assertions = "1"
