[workspace]
members = [
  "vector2d",
  "geometry",
  "physics",
  "format_core",
  "format_json",
  "format_trk",
  "format_sol",
  "format_converter",
  "spatial_grid",
  "color",
  "lcg_random",
]
resolver = "3"
