[workspace]
members = [
  "vector2d",
  "geometry",
  "lr_format_core",
  "lr_format_json",
  "lr_format_trk",
  "lr_format_sol",
  "lr_physics_engine",
  "lr_physics_grid",
  "lr_physics_line_store",
  "color",
  "lcg_random",
  "amf0",
  "lr_studio",
  "quick_byte",
]
resolver = "3"
