[workspace]
members = [
  "vector2d",
  "geometry",
  "lr_physics_engine",
  "lr_types",
  "lr_format_json",
  "lr_format_trk",
  "lr_format_sol",
  "lr_physics_grid",
  "color",
  "lcg_random",
  "amf0",
  "lr_studio",
]
resolver = "3"
