[package]
edition = "2024"
name = "lr_physics_line_store"
version = "0.1.0"

[dependencies]
geometry = {path = "../geometry"}
lr_physics_grid = {path = "../lr_physics_grid"}
vector2d = {path = "../vector2d"}
