[package]
edition = "2024"
name = "format_json"
version = "0.1.0"

[dependencies]
format_core = {version = "0.1.0", path = "../format_core"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
vector2d = {path = "../vector2d"}
