[package]
edition = "2024"
name = "lr_format_trk"
version = "0.1.0"

[dependencies]
byteorder = "1"
color = {path = "../color"}
lr_types = {path = "../lr_types"}
thiserror = "2"
vector2d = {path = "../vector2d"}

[dev-dependencies]
pretty_assertions = "1"
